# Generated by Django 5.1.7 on 2025-03-16 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True)),
                ('task_completed', models.BooleanField(default=False)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_end', models.DateField(blank=True, null=True)),
                ('task_priority', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
