# Generated by Django 5.1.7 on 2025-03-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
